In [57]:
import pandas as pd
import re

In [58]:
def remove_message_timestamp(message):
    regex = r"'t': \d+\.\d+, "
    new_message = re.sub(regex, '', message)
    return new_message

In [59]:
df = pd.read_csv('/home/mayki/Documentos/GIT/SSEDG/dados/original/completo/dados-23-07-2024_21-06-39.csv')
# df.sort_values(by='timeStamp', ascending=True, inplace=True)
df.head()

,device,devId,productKey,message,sensorType,group,userAction,activityUserAction,timeStamp,space
0,BANHEIRO_02_SENSOR_PRESENCA-010,disp7a70ae626a9db511948d2ca2ffef0cff,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,USAR_BANHEIRO_02,2024-06-23 07:05:07.600740,BANHEIRO_02
1,BANHEIRO_02_SENSOR_PRESENCA-010,disp7a70ae626a9db511948d2ca2ffef0cff,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:21.267971,BANHEIRO_02
2,CORREDOR_SENSOR_PRESENCA-027,dispf7c434c69ee54cf81abcfb1b8c79a9e3,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:35.535416,CORREDOR
3,CORREDOR_SENSOR_PRESENCA-027,dispf7c434c69ee54cf81abcfb1b8c79a9e3,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:50.235101,CORREDOR
4,COZINHA_SENSOR_PRESENCA-021,disp16b045cc84bdde80b25c98cb4bb5575f,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:50.508948,COZINHA

In [60]:
df['message'] = df['message'].apply(remove_message_timestamp)
df.head()

,device,devId,productKey,message,sensorType,group,userAction,activityUserAction,timeStamp,space
0,BANHEIRO_02_SENSOR_PRESENCA-010,disp7a70ae626a9db511948d2ca2ffef0cff,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,USAR_BANHEIRO_02,2024-06-23 07:05:07.600740,BANHEIRO_02
1,BANHEIRO_02_SENSOR_PRESENCA-010,disp7a70ae626a9db511948d2ca2ffef0cff,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:21.267971,BANHEIRO_02
2,CORREDOR_SENSOR_PRESENCA-027,dispf7c434c69ee54cf81abcfb1b8c79a9e3,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:35.535416,CORREDOR
3,CORREDOR_SENSOR_PRESENCA-027,dispf7c434c69ee54cf81abcfb1b8c79a9e3,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:50.235101,CORREDOR
4,COZINHA_SENSOR_PRESENCA-021,disp16b045cc84bdde80b25c98cb4bb5575f,0s9d8f9s0d8f0s9df8s0f8,"{'status': [{'code': 'presence_state', 'value'...",sensor,"['Gustavo', 'Amanda']",Amanda,CAFE_DA_MANHA,2024-06-23 07:13:50.508948,COZINHA

In [61]:
unique_devices = df['device'].unique()
unique_devices

array(['BANHEIRO_02_SENSOR_PRESENCA-010', 'CORREDOR_SENSOR_PRESENCA-027',
       'COZINHA_SENSOR_PRESENCA-021', 'COZINHA_CAFETEIRA-020',
       'SALA_SENSOR_PRESENCA-004', 'SALA_TV-001',
       'SALA_AR_CONDICIONADO-002', 'QUARTO_01_SENSOR_PRESENCA-014',
       'SALA_LAMPADA-003', 'BANHEIRO_02_LAMPADA-009',
       'QUARTO_01_AR_CONDICIONADO-012', 'BANHEIRO_01_LAMPADA-008',
       'COZINHA_LAMPADA-019', 'ESCRITORIO_SENSOR_PRESENCA-007',
       'ESCRITORIO_AR_CONDICIONADO-006', 'QUARTO_01_LAMPADA-011',
       'ESCRITORIO_LAMPADA-005'], dtype=object)

In [62]:
for device in unique_devices:
    result = (df[df['device'] == device]['message'].shift(1) == df[df['device'] == device]['message']).sum()
    print(f'{device}: {result}')

BANHEIRO_02_SENSOR_PRESENCA-010: 0
CORREDOR_SENSOR_PRESENCA-027: 0
COZINHA_SENSOR_PRESENCA-021: 0
COZINHA_CAFETEIRA-020: 0
SALA_SENSOR_PRESENCA-004: 0
SALA_TV-001: 0
SALA_AR_CONDICIONADO-002: 0
QUARTO_01_SENSOR_PRESENCA-014: 0
SALA_LAMPADA-003: 0
BANHEIRO_02_LAMPADA-009: 0
QUARTO_01_AR_CONDICIONADO-012: 0
BANHEIRO_01_LAMPADA-008: 0
COZINHA_LAMPADA-019: 0
ESCRITORIO_SENSOR_PRESENCA-007: 0
ESCRITORIO_AR_CONDICIONADO-006: 0
QUARTO_01_LAMPADA-011: 0
ESCRITORIO_LAMPADA-005: 0

In [63]:
duplicated_dict = {}
for device in unique_devices:
    result = df[df['device'] == device].reset_index()[(df[df['device'] == device]['message'].shift(1) == df[df['device'] == device]['message']).values].index.tolist()
    if len(result) > 0:
        duplicated_dict[device] = result
    print(f'{device}: {result}')

BANHEIRO_02_SENSOR_PRESENCA-010: []
CORREDOR_SENSOR_PRESENCA-027: []
COZINHA_SENSOR_PRESENCA-021: []
COZINHA_CAFETEIRA-020: []
SALA_SENSOR_PRESENCA-004: []
SALA_TV-001: []
SALA_AR_CONDICIONADO-002: []
QUARTO_01_SENSOR_PRESENCA-014: []
SALA_LAMPADA-003: []
BANHEIRO_02_LAMPADA-009: []
QUARTO_01_AR_CONDICIONADO-012: []
BANHEIRO_01_LAMPADA-008: []
COZINHA_LAMPADA-019: []
ESCRITORIO_SENSOR_PRESENCA-007: []
ESCRITORIO_AR_CONDICIONADO-006: []
QUARTO_01_LAMPADA-011: []
ESCRITORIO_LAMPADA-005: []

In [64]:
duplicated_df = pd.DataFrame()
for device in duplicated_dict.keys():
    for index in duplicated_dict[device]:
        duplicated_df = pd.concat([duplicated_df, df[df['device'] == device].iloc[index-1:index+1]])
duplicated_df

Empty DataFrame
Columns: []
Index: []